name: CI

on: [push, pull_request]

jobs:
  build:
    runs-on: self-hosted
    steps:
    - uses: actions/checkout@v2
    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
    - name: Run a one-line script
      run: >-      
        container_id=$(docker ps --filter "status=running" --format "{{.ID}} {{.Image}}" | grep server | cut -d " " -f 1)
        
        if [ -n "$container_id" ]; then
         docker cp /var/lib/jenkins/workspace/devops/. "$container_id":/usr/share/nginx/html
         docker stop $container_id
         docker start server
        else
         docker build -t server /var/lib/jenkins/workspace/devops
         docker run --name server -d -p 9090:80 server
